#!/bin/sh
exec 2>&1

CONFIG="/container/config/haproxy/haproxy.cfg"
EXTRAOPTS="-de -m 512"

mkdir -p /run/haproxy
chown haproxy.root /run/haproxy

exec /usr/sbin/haproxy -Ws -f $CONFIG -p /var/run/haproxy.pid $EXTRAOPTS
